[theme]
base = "dark"
primaryColor = "#EE812E"          # tweak as you like
backgroundColor = "#0b0423"       # matches your .stApp background
secondaryBackgroundColor = "#151238"
textColor = "#ffffff"
